# Central registry — imports everything and exposes
# TOOL_REGISTRY and TOOL_DEFINITIONS to brain.py

from agent import AGENT_DEFINITIONS, AGENT_TOOLS
from tools.email_tools import EMAIL_DEFINITIONS_LIST, EMAIL_TOOLS_DICT
from goals import GOAL_DEFINITIONS, GOAL_TOOLS
from graph_memory import GRAPH_DEFINITIONS, GRAPH_TOOLS
from self_awareness import SELF_DEFINITIONS, SELF_TOOLS
from tools.browser_tools import BROWSER_DEFINITIONS, BROWSER_TOOLS
from tools.calendar_tools import CALENDAR_DEFINITIONS, CALENDAR_TOOLS
from tools.code_tools import CODE_DEFINITIONS, CODE_TOOLS
from tools.communication_tools import COMMUNICATION_DEFINITIONS, COMMUNICATION_TOOLS
from tools.computer_tools import COMPUTER_DEFINITIONS, COMPUTER_TOOLS
from tools.discord_tools import DISCORD_DEFINITIONS, DISCORD_TOOLS
from tools.file_tools import FILE_DEFINITIONS, FILE_TOOLS
from tools.ingest_tools import INGEST_DEFINITIONS, INGEST_TOOLS
from tools.finance_tools import FINANCE_DEFINITIONS, FINANCE_TOOLS

# OAuth-dependent tools (less commonly used for tool-calling, placed last due to Groq 128 limit)
from tools.github_tools import GITHUB_DEFINITIONS, GITHUB_TOOLS
from tools.gmail_tools import GMAIL_DEFINITIONS, GMAIL_TOOLS
from tools.google_docs_tools import DOCS_DEFINITIONS, DOCS_TOOLS
from tools.google_drive_tools import DRIVE_DEFINITIONS, DRIVE_TOOLS
from tools.google_forms_tools import FORMS_DEFINITIONS, FORMS_TOOLS
from tools.google_sheets_tools import SHEETS_DEFINITIONS, SHEETS_TOOLS
from tools.google_slides_tools import SLIDES_DEFINITIONS, SLIDES_TOOLS
from tools.inspect_tools import INSPECT_DEFINITIONS, INSPECT_TOOLS
from tools.maps_tools import MAPS_DEFINITIONS, MAPS_TOOLS
from tools.news_tools import NEWS_DEFINITIONS, NEWS_TOOLS
from tools.reminders_tools import REMINDERS_DEFINITIONS, REMINDERS_TOOLS
from tools.sandbox_tools import SANDBOX_DEFINITIONS, SANDBOX_TOOLS
from tools.serpapi_tools import SERPAPI_DEFINITIONS, SERPAPI_TOOLS
from tools.spotify_tools import SPOTIFY_DEFINITIONS, SPOTIFY_TOOLS
from tools.system_tools import SYSTEM_DEFINITIONS, SYSTEM_TOOLS
from tools.vision_tools import VISION_DEFINITIONS, VISION_TOOLS

# Merge everything into one registry
TOOL_REGISTRY = {}
TOOL_REGISTRY.update(SYSTEM_TOOLS)
TOOL_REGISTRY.update(SPOTIFY_TOOLS)
TOOL_REGISTRY.update(CALENDAR_TOOLS)
TOOL_REGISTRY.update(FILE_TOOLS)
TOOL_REGISTRY.update(INGEST_TOOLS)
TOOL_REGISTRY.update(BROWSER_TOOLS)
TOOL_REGISTRY.update(DISCORD_TOOLS)
TOOL_REGISTRY.update(COMMUNICATION_TOOLS)
TOOL_REGISTRY.update(VISION_TOOLS)
TOOL_REGISTRY.update(COMPUTER_TOOLS)
TOOL_REGISTRY.update(CODE_TOOLS)
TOOL_REGISTRY.update(SANDBOX_TOOLS)
TOOL_REGISTRY.update(SELF_TOOLS)
TOOL_REGISTRY.update(GOAL_TOOLS)
TOOL_REGISTRY.update(AGENT_TOOLS)
TOOL_REGISTRY.update(GRAPH_TOOLS)
TOOL_REGISTRY.update(FINANCE_TOOLS)
TOOL_REGISTRY.update(MAPS_TOOLS)
TOOL_REGISTRY.update(NEWS_TOOLS)
TOOL_REGISTRY.update(REMINDERS_TOOLS)
TOOL_REGISTRY.update(SERPAPI_TOOLS)
TOOL_REGISTRY.update(INSPECT_TOOLS)
TOOL_REGISTRY.update(EMAIL_TOOLS_DICT)
# OAuth
TOOL_REGISTRY.update(GITHUB_TOOLS)
TOOL_REGISTRY.update(GMAIL_TOOLS)
TOOL_REGISTRY.update(DRIVE_TOOLS)
TOOL_REGISTRY.update(SHEETS_TOOLS)
TOOL_REGISTRY.update(DOCS_TOOLS)
TOOL_REGISTRY.update(SLIDES_TOOLS)
TOOL_REGISTRY.update(FORMS_TOOLS)

TOOL_DEFINITIONS = (
    SYSTEM_DEFINITIONS
    + SPOTIFY_DEFINITIONS
    + CALENDAR_DEFINITIONS
    + FILE_DEFINITIONS
    + INGEST_DEFINITIONS
    + BROWSER_DEFINITIONS
    + DISCORD_DEFINITIONS
    + COMMUNICATION_DEFINITIONS
    + VISION_DEFINITIONS
    + COMPUTER_DEFINITIONS
    + CODE_DEFINITIONS
    + SANDBOX_DEFINITIONS
    + SELF_DEFINITIONS
    + GOAL_DEFINITIONS
    + AGENT_DEFINITIONS
    + GRAPH_DEFINITIONS
    + FINANCE_DEFINITIONS
    + MAPS_DEFINITIONS
    + NEWS_DEFINITIONS
    + REMINDERS_DEFINITIONS
    + SERPAPI_DEFINITIONS
    + INSPECT_DEFINITIONS
    + EMAIL_DEFINITIONS_LIST
    # OAuth
    + GITHUB_DEFINITIONS
    + GMAIL_DEFINITIONS
    + DRIVE_DEFINITIONS
    + SHEETS_DEFINITIONS
    + DOCS_DEFINITIONS
    + SLIDES_DEFINITIONS
    + FORMS_DEFINITIONS
)

__all__ = ["TOOL_REGISTRY", "TOOL_DEFINITIONS"]
